### ISSUE TITLE
passing values to setInterval example

### ISSUE THREAD

**Issue by theednaffattack** [AlexanderElias/promise-tool#1]
Hey there, I'm having trouble passing an array to the method function shown in the timers example.  I get method.apply errors when I try. This is a pretty beginner-ish question and I'm sorry. I've tried to wrap my head around this for a few days and I can't quite get it sorted.

```javascript
PromiseTool2.setInterval(delay, method(myArray)).then(function(args) {
  // this refers to interval

  // this args variable only shows what the top of the if method (meaning if 'true') returns,
  // so nothing happens until the interval is over
  infoLogger.log(args);
  infoLogger.log("interval done");
});

```

**Comment by xeaone** [comment]
I think it is because you are passing the result of your `method` function. Try replacing `method(myArray)` with this `method.bind(null, myArray)`. Let me know if that solves the issue.

**Comment by theednaffattack** [comment]
That worked perfectly, thanks. It's not your job to teach me JS so I appreciate your explaining things in addition to giving me the code fix.

I hate to pollute your Issues but I'm trying to read up more and practice this. If you'll forgive my two part question:
Is your reply saying that the first time I attempted to pass in the function _after execution_ (the result)?  So when I tried to pass in the function the first time there was no "this" present, and also no arguments? 

I tried to read up [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind) and [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply).

**Comment by xeaone** [comment]
It is no problem. Willing to help. Feel free to take down my email for future questions.

Your answer to your question is correct.

The `method()` is a invocation of the function similar to `.apply` and `.call`. So in your example the function was executed/invoked. If your method returned a value the value would then be passed into `setInterval` as a parameter other wise the default return value from a function is `undefined`.  The `.bind` basically creates a new copy of that function and returns that copy but does not execute/invoke the function.
